import { useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";
import { ArrowLeft, BookOpen, Clock } from "lucide-react";

// Mock database of articles
const articlesData: Record<string, { title: string; category: string; readTime: string; content: string }> = {
  "how-to-write-the-perfect-thumbnail-prompt": {
    title: "How to write the perfect thumbnail prompt",
    category: "Thumbnail Generation",
    readTime: "4 min read",
    content: `
Writing a good prompt is the key to getting exactly what you want from ThumbForge. Here are the core principles:

### 1. Be descriptive but concise
Instead of "make it cool", say "make it look epic with neon blue and purple lighting, futuristic city background."

### 2. Specify the emotion
The AI relies heavily on emotional keywords. Words like "shocked", "angry", "insane reaction", or "focused" will drastically change how the face insert or character is rendered.

### 3. Mention the game context
Always mention the game if you want the environment to match. E.g., "Minecraft survival realistic shaders" or "Roblox Tycoon colorful and bright".

### 4. Use the Style Modifiers
You don't always need to type everything. You can use our built-in style buttons (like "Hyper-Realistic", "Cartoon", "3D Render") after typing a basic prompt to enhance it automatically.
    `
  },
  "using-the-skin-replacer-tool": {
    title: "Using the Skin Replacer tool",
    category: "Thumbnail Generation",
    readTime: "3 min read",
    content: `
The Skin Replacer is one of ThumbForge's most powerful tools, allowing you to insert your own gaming skin (like Minecraft or Roblox) into any thumbnail.

### Step 1: Upload your skin file
In the Studio, go to the Skin Replacer panel. Upload your raw skin file (e.g., standard 64x64 Minecraft PNG format).

### Step 2: Choose the pose
You don't need to pose the skin beforehand. The AI will look at the original character in the thumbnail and automatically match their pose.

### Step 3: Apply and refine
Click "Replace Skin". The AI will generate the new character. If the lighting doesn't match perfectly, you can use a follow-up prompt like "fix lighting on character to match background sunset".
    `
  },
  "understanding-styles-and-lighting": {
    title: "Understanding styles and lighting",
    category: "Thumbnail Generation",
    readTime: "2 min read",
    content: `
Lighting makes or breaks a thumbnail. The AI automatically tries to match standard YouTube lighting (high contrast, rim lights), but you can override this.

**Best keywords for lighting:**
- "Cinematic rim lighting"
- "Neon cyberpunk glow"
- "Bright sunny daylight, vibrant colors"
- "Dark moody atmosphere, dramatic shadows"

If you're making a scary gaming video, use words like "dark, eerie, flashlight beam, high contrast". For a fun tutorial, use "bright, colorful, high key lighting, soft shadows".
    `
  },
  "aspect-ratios-and-export-quality": {
    title: "Aspect ratios and export quality",
    category: "Thumbnail Generation",
    readTime: "1 min read",
    content: `
All thumbnails generated by ThumbForge are strictly fixed to YouTube's recommended **16:9 aspect ratio** (1280x720 or 1920x1080).

**Export Options:**
- **Free Plan:** 720p export (standard definition, perfect for mobile viewers) plus a small watermark.
- **Starter Plan & Above:** Full 1080p HD export, no watermark.
- **Pro Plan:** 4K upscaling available for maximum crispness on large displays.

You can download your generation straight to your device as a highly optimized JPG or PNG from the Studio Export menu.
    `
  },
  "how-to-change-your-email-address": {
    title: "How to change your email address",
    category: "Account & Profile",
    readTime: "1 min read",
    content: `
To update your email address, please follow these steps:

1. Navigate to your Account Settings via the dashboard sidebar.
2. Under "Profile Information", click "Edit Email".
3. Enter your new email address.
4. You will receive a verification link to your new email. Click it to confirm the change.

*Note: If you signed in using Discord or Google Oauth, your email is tied to that provider.*
    `
  },
  "resetting-a-forgotten-password": {
    title: "Resetting a forgotten password",
    category: "Account & Profile",
    readTime: "1 min read",
    content: `
If you've forgotten your password, you can reset it easily:

1. Go to the Sign In page.
2. Click on "Forgot password?".
3. Enter the email address associated with your thumbForge account.
4. We will send you a secure link to reset your password.
    `
  },
  "linking-your-discord-account": {
    title: "Linking your Discord account",
    category: "Account & Profile",
    readTime: "2 min read",
    content: `
Linking your Discord account allows you to fast-login and gives you access to the private ThumbForge Discord community channels (Pro users only).

To link your account:
Go to Settings > Connections. Click "Connect Discord". You will be redirected to Discord to authorize the connection.
    `
  },
  "deleting-your-account": {
    title: "Deleting your account",
    category: "Account & Profile",
    readTime: "1 min read",
    content: `
You can request account deletion at any time from your Account Settings page. Scroll to the bottom and click the red "Delete Account" button.

**Warning:** This action is permanent. All your generated thumbnails, remaining credits, and subscription data will be permanently erased.
    `
  },
  "how-does-the-credit-system-work": {
    title: "How does the credit system work?",
    category: "Billing & Credits",
    readTime: "2 min read",
    content: `
ThumbForge operates on a credit system for AI generations.

- **1 Credit** = 1 Standard Generation or 1 Quick Edit.
- **2 Credits** = 1 Face Insert or Skin Replacement.
- **5 Credits** = 1 4K Upscale.

Free tier users receive 10 credits per month that do not roll over. Paid subscribers receive their allotment monthly, and any unused paid credits roll over up to a maximum of 3x your monthly allowance.
    `
  },
  "upgrading-to-a-pro-plan": {
    title: "Upgrading to a Pro plan",
    category: "Billing & Credits",
    readTime: "1 min read",
    content: `
You can upgrade to a Pro plan at any time to instantly receive more credits and unlock premium tools like Face Insert AI and watermark removal.

Visit the [Pricing](#pricing) section or your Billing dashboard, select a plan, and complete checkout. Your account will automatically upgrade within seconds.
    `
  },
  "how-to-cancel-your-subscription": {
    title: "How to cancel your subscription",
    category: "Billing & Credits",
    readTime: "1 min read",
    content: `
You can cancel your active subscription at any time. Go to Settings > Billing, and click "Manage Subscription". You will be taken to the Whop customer portal where you can cancel.

Your premium benefits and remaining credits will remain active until the end of your current billing cycle.
    `
  },
  "refund-policy": {
    title: "Refund policy",
    category: "Billing & Credits",
    readTime: "2 min read",
    content: `
Due to the high computational costs associated with AI generation, we generally **do not offer refunds** for subscriptions once credits have been consumed.

If you made an accidental purchase and have not used ANY paid credits, contact our support team within 48 hours for a full refund evaluation. Read our [Terms of Service](/terms) for complete details.
    `
  }
};

const Article = () => {
  const { slug } = useParams();
  const navigate = useNavigate();
  
  const article = slug ? articlesData[slug] : undefined;

  useEffect(() => {
    if (!article && slug) {
      navigate('/help', { replace: true });
    }
    if (article) {
       document.title = `${article.title} – ThumbForge Help`;
    }
  }, [article, navigate, slug]);

  if (!article) return null;

  return (
    <div className="min-h-screen bg-black text-white selection:bg-white/20 flex flex-col">
      <Header />
      
      <main className="flex-1 pt-32 pb-24">
        <article className="container max-w-3xl px-4 md:px-6 mx-auto">
          
          <Link to="/help" className="inline-flex items-center gap-2 text-sm text-white/40 hover:text-white transition-colors mb-8">
            <ArrowLeft className="h-4 w-4" />
            Back to Help Center
          </Link>

          <div className="mb-12">
            <div className="flex items-center gap-4 text-sm text-white/40 font-light mb-4">
              <span className="flex items-center gap-1.5"><BookOpen className="h-3.5 w-3.5" /> {article.category}</span>
              <span>•</span>
              <span className="flex items-center gap-1.5"><Clock className="h-3.5 w-3.5" /> {article.readTime}</span>
            </div>
            <h1 className="text-3xl md:text-5xl font-medium tracking-tight text-white mb-8">
              {article.title}
            </h1>
            <div className="h-px bg-white/10 w-full" />
          </div>

          <div className="prose prose-invert prose-p:text-white/70 prose-a:text-white prose-strong:text-white prose-ul:text-white/70 max-w-none">
            <ReactMarkdown>{article.content.trim()}</ReactMarkdown>
          </div>

        </article>
      </main>

      <Footer />
    </div>
  );
};

export default Article;
