import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-black text-white selection:bg-white/20 flex flex-col">
      <Header />
      <main className="flex-1 container max-w-4xl px-4 md:px-6 pt-32 pb-24">
        <h1 className="text-4xl md:text-5xl font-medium tracking-tight mb-8">Terms of Service</h1>
        <div className="prose prose-invert max-w-none text-white/70 font-light space-y-6">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="text-2xl font-medium text-white mt-12 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using ThumbForge ("the Service"), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">2. Merchant of Record</h2>
          <p>
            Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle handles all customer service inquiries and returns. By purchasing through Paddle, you also agree to Paddle's Terms of Use and Privacy Policy.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">3. Description of Service</h2>
          <p>
            ThumbForge provides AI-powered image generation and editing tools. We grant you a non-exclusive, non-transferable, revocable license to use the Service for your personal or commercial projects, subject to these terms.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">4. Subscriptions and Billing</h2>
          <p>
            Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in advance on a recurring and periodic basis. Billing cycles are set either on a monthly or annual basis. At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or ThumbForge cancels it.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">5. Intellectual Property and Content Rights</h2>
          <p>
            You retain all rights to the images you upload to the Service. Regarding the content generated by the AI: ThumbForge grants you a worldwide, royalty-free, and non-exclusive license to use, reproduce, modify, and display the generated images for any purpose, including commercial use. You are responsible for ensuring that your use of the generated content does not infringe on third-party rights.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">6. Prohibited Uses</h2>
          <p>
            You may use the Service only for lawful purposes. You agree not to use the Service:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>To generate content that is illegal, harmful, or promotes violence or discrimination.</li>
            <li>To generate highly explicit or strictly NSFW content that violates our safety filters.</li>
            <li>In any way that infringes upon the rights of others or inhibits their use of the Service.</li>
            <li>To attempt to decompile, reverse engineer, or hack any part of the platform.</li>
          </ul>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">7. Limitation of Liability</h2>
          <p>
            In no event shall ThumbForge, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">8. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with the laws of Germany, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
          </p>

          <h2 className="text-2xl font-medium text-white mt-12 mb-4">9. Contact</h2>
          <p>
            For any questions regarding these Terms, please contact us at support@thumbforge.com or through our Discord community.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TermsOfService;

